// Date: 21/07/2014 20:22:19
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.callumhutchy.runecraft2.blocks.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class AltarRuneModel extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape71;
    ModelRenderer Shape72;
    ModelRenderer Shape73;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape4;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape111;
    ModelRenderer Shape101;
    ModelRenderer Rune1;
    ModelRenderer Rune2;
    ModelRenderer Rune3;
    ModelRenderer Rune4;
    ModelRenderer Rune5;
    ModelRenderer Rune_6;
  
  public AltarRuneModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 9, 28);
      Shape1.addBox(0F, 0F, 0F, 10, 1, 10);
      Shape1.setRotationPoint(-5F, 23F, -5F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 10, 29);
      Shape2.addBox(0F, 0F, 0F, 8, 1, 8);
      Shape2.setRotationPoint(-4F, 22F, -4F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 10, 30);
      Shape3.addBox(0F, 0F, 0F, 6, 1, 6);
      Shape3.setRotationPoint(-3F, 21F, -3F);
      Shape3.setTextureSize(64, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 13, 30);
      Shape5.addBox(0F, 0F, 0F, 6, 1, 6);
      Shape5.setRotationPoint(-3F, 13F, -3F);
      Shape5.setTextureSize(64, 64);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 9, 28);
      Shape6.addBox(0F, 0F, 0F, 10, 1, 10);
      Shape6.setRotationPoint(-5F, 12F, -5F);
      Shape6.setTextureSize(64, 64);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 0, 33);
      Shape7.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape7.setRotationPoint(3F, 13F, 3F);
      Shape7.setTextureSize(64, 64);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape71 = new ModelRenderer(this, 0, 33);
      Shape71.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape71.setRotationPoint(3F, 13F, -4F);
      Shape71.setTextureSize(64, 64);
      Shape71.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape72 = new ModelRenderer(this, 0, 33);
      Shape72.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape72.setRotationPoint(-4F, 13F, 3F);
      Shape72.setTextureSize(64, 64);
      Shape72.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape73 = new ModelRenderer(this, 0, 33);
      Shape73.addBox(0F, 0F, 0F, 1, 9, 1);
      Shape73.setRotationPoint(-4F, 13F, -4F);
      Shape73.setTextureSize(64, 64);
      Shape73.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 6, 26);
      Shape8.addBox(0F, 0F, 0F, 12, 1, 12);
      Shape8.setRotationPoint(-6F, 11F, -6F);
      Shape8.setTextureSize(64, 64);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 0, 49);
      Shape9.addBox(0F, 0F, 0F, 14, 1, 14);
      Shape9.setRotationPoint(-7F, 10F, -7F);
      Shape9.setTextureSize(64, 64);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 10, 32);
      Shape4.addBox(0F, 0F, 0F, 4, 1, 4);
      Shape4.setRotationPoint(-2F, 20F, -2F);
      Shape4.setTextureSize(64, 64);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape10 = new ModelRenderer(this, 0, 0);
      Shape10.addBox(0F, 0F, 0F, 13, 1, 1);
      Shape10.setRotationPoint(-7F, 9F, 6F);
      Shape10.setTextureSize(64, 64);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 0, 0);
      Shape11.addBox(0F, 0F, 0F, 1, 1, 13);
      Shape11.setRotationPoint(6F, 9F, -6F);
      Shape11.setTextureSize(64, 64);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape111 = new ModelRenderer(this, 0, 0);
      Shape111.addBox(0F, 0F, 0F, 1, 1, 13);
      Shape111.setRotationPoint(-7F, 9F, -7F);
      Shape111.setTextureSize(64, 64);
      Shape111.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape101 = new ModelRenderer(this, 0, 0);
      Shape101.addBox(0F, 0F, 0F, 13, 1, 1);
      Shape101.setRotationPoint(-6F, 9F, -7F);
      Shape101.setTextureSize(64, 64);
      Shape101.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Rune1 = new ModelRenderer(this, 33, 0);
      Rune1.addBox(0F, 0F, 0F, 8, 1, 8);
      Rune1.setRotationPoint(-4F, 9F, -4F);
      Rune1.setTextureSize(64, 64);
      Rune1.mirror = true;
      setRotation(Rune1, 0F, 0F, 0F);
      Rune2 = new ModelRenderer(this, 42, 10);
      Rune2.addBox(0F, 0F, 0F, 1, 1, 6);
      Rune2.setRotationPoint(-5F, 9F, -3F);
      Rune2.setTextureSize(64, 64);
      Rune2.mirror = true;
      setRotation(Rune2, 0F, 0F, 0F);
      Rune3 = new ModelRenderer(this, 42, 10);
      Rune3.addBox(0F, 0F, 0F, 1, 1, 6);
      Rune3.setRotationPoint(4F, 9F, -3F);
      Rune3.setTextureSize(64, 64);
      Rune3.mirror = true;
      setRotation(Rune3, 0F, 0F, 0F);
      Rune4 = new ModelRenderer(this, 42, 10);
      Rune4.addBox(0F, 0F, 0F, 6, 1, 1);
      Rune4.setRotationPoint(-3F, 9F, 4F);
      Rune4.setTextureSize(64, 64);
      Rune4.mirror = true;
      setRotation(Rune4, 0F, 0F, 0F);
      Rune5 = new ModelRenderer(this, 42, 10);
      Rune5.addBox(0F, 0F, 0F, 6, 1, 1);
      Rune5.setRotationPoint(-3F, 9F, -5F);
      Rune5.setTextureSize(64, 64);
      Rune5.mirror = true;
      setRotation(Rune5, 0F, 0F, 0F);
      Rune_6 = new ModelRenderer(this, 40, 18);
      Rune_6.addBox(0F, 0F, 0F, 6, 1, 6);
      Rune_6.setRotationPoint(-3F, 8F, -3F);
      Rune_6.setTextureSize(64, 64);
      Rune_6.mirror = true;
      setRotation(Rune_6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape71.render(f5);
    Shape72.render(f5);
    Shape73.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape4.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape111.render(f5);
    Shape101.render(f5);
    Rune1.render(f5);
    Rune2.render(f5);
    Rune3.render(f5);
    Rune4.render(f5);
    Rune5.render(f5);
    Rune_6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
